remote_theme: JJPPeters/jekyll-graphene-theme

# setup
title: EMPeaks # this is the main title in the header
tagline: Python TEM analysis # this is the text that appears next to the title
baseurl: /EMPeaks # the subpath of your site, e.g. /blog
url: https://jjppeters.github.io/EMPeaks/ # the base hostname & protocol for your site, e.g. http://example.com
repository: JJPPeters/EMPeaks

# contact
author:
  name: J. J. P. Peters
  github_username: JJPPeters
  url: https://github.com/JJPPeters
  email: jonathanjppeters@gmail.com